### ISSUE TITLE
Order for multiple family members (with multiples auth codes) are not working

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#105]
If I have 3 approved auth codes it should ask me how many meals I want to order once I make the selection up to the number of auth codes approved.

**Comment by john3parker** [comment]
I'm looking at this but if you have a solution ready to go feel free to jump on it.

**Comment by john3parker** [comment]
Added new transactional phase to request # of meals if user has more than 1 authorization code.
