### ISSUE TITLE
Order Limit not being recognized

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#110]
Users have a preset limit (currently 1) of orders they can place per day.    System is not currently limit orders per customer per day

**Comment by darargon** [comment]
Since I think this is a bit ambiguous. Should the limit reset at midnight every night, or should it reset 24 hours after the last order was placed?

**Comment by KKAY99** [comment]
Reset at midnight.  Limit is per calendar day

**Comment by john3parker** [comment]
To clarify -- 1 meal per day per activation code. So if a User has 4 valid activation codes (family of 4) they should be able to get 4 meals per day.

**Comment by john3parker** [comment]
Added code to check for max meals.. if a user has 4 activation codes she'll be able to order 4 meals in a 24 hour period.

**Comment by KKAY99** [comment]
@john3parker  - a 24 hour window is goign to confuse people. If we're not limiting it a calendar day I'd suggest a 12 or 18 hour window so you don't have people trying to figure out when they can order lunch and a cascading time window.  If you tried to order lunch every day at 1 with a 24 hour window you would have to order later each day
