### ISSUE TITLE
Invalid Response Code on Please sign up first by saying REGISTER message

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#111]
Need to return status 200 - not an error exception (which triggers West Event response

**Comment by Yichao-Yu** [comment]
Karl, how can we reproduce the issue?

**Comment by KKAY99** [comment]
Suggest replace  

throw new HNIException("Please sign up first by saying REGISTER")

with

return "Please sign up first by saying REGISTER before ordering a meal.";

**Comment by KKAY99** [comment]
Yicaho, Try ordering a meal before registration.

I believe the issue is we throw an exception rather than return a status
code

**Comment by john3parker** [comment]
OrderProcessor.handleEvent() will return a message if the user tries to order a meal but isn't registered. HTTP STATUS will be 200.
