### ISSUE TITLE
Confimation message error

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#127]
Got back a bad configmration message from order - "You've chosen %s at %s" Reply CONFIRM

**Comment by jeff3parker** [comment]
specification called for 3 string inputs, but only provided 2.  Output should now read as

Your order has been placed and should be ready to pick up shortly from %s at %s %s.
Your order has been placed and should be ready to pick up shortly from SUBWAY at ADDRESS CITY.
