### ISSUE TITLE
REDO on order causes multiple order items

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#143]
If a user selects REDO they end up with multiple orders for the original item and second item.

Example 

Put in address 805 Moberly Lane
Select 2 (Chicken Tacos)
REDO
Select 1 (Subway)
CONFIRM

order items  table gets filled with an order for Chicken Tacos and Sandwich

**Comment by Yichao-Yu** [comment]
i think redo should reset the partial order status to CHOOSING_MENU_ITEM. 
But what is the meaning of redo in multiple order scenario? Redo current order?

**Comment by KKAY99** [comment]
I would say REDO should reset the status CHOOSING_MENU_ITEM and clear out any selections made so far.

**Comment by Yichao-Yu** [comment]
+----+---------+----------------------+--------------+----------------+--------------------+-------------------+-----------------------------------+
| id | user_id | provider_location_id | menu_item_id | chosen_menu_id | chosen_provider_id | transaction_phase | address                           |
+----+---------+----------------------+--------------+----------------+--------------------+-------------------+-----------------------------------+
|  2 |       9 |                 NULL |         NULL |           NULL |               NULL | 1                 | 1251 Phoenician way, Columbus, OH |
| 70 |      15 |                 NULL |         NULL |           NULL |                 17 | 4                 | 805 Moberly Lane                  |
| 82 |      16 |                 NULL |         NULL |           NULL |               NULL | 1                 | NULL                              |
| 86 |      11 |                 NULL |         NULL |           NULL |               NULL | 1                 | NULL                              |
| 88 |      22 |                 NULL |         NULL |           NULL |                     22| 2                 | 1 Main Rogers AR                  |
+----+---------+----------------------+--------------+----------------+--------------------+-------------------+-----------------------------------+
Small caveat, the chosen provider is not reset after REDO (See id 88). But this does not affect the logic. 
another PR to fix that https://github.com/hungernotimpossible/hni/pull/147
