### ISSUE TITLE
GeoLocation didn't find closest Subway 

### ISSUE THREAD

**Issue by john3parker** [hungernotimpossible/hni#154]
A meal was started with this address. "S thompson St. Fayetteville ar 72701" 
This is the Subway 100 yards from that  location. I'm not sure if the lat/long coordinates are correct. 

| 10 | Subway    | 5204 S Thompson |               | Springdale | AR    | 72764 | -94.1459545 | 36.1346177 | -6       |

But the user received this list.. 
Reply 1, 2 or 3 to choose your meal. 1) Ham Sandwich from Subway 616 North Garland Avenue Fayetteville. 2) Ham Sandwich from Subway 1680 North College Ave. Fayetteville. 3) Chicken Soft Tacos (3) from Taco Bell 2055 W Martin Luther King Blvd Fayetteville.

This is the Google Maps url of the Subway on S. Thompson. Lat/Long are different from database. 
https://www.google.com/maps/place/Subway/@36.1338612,-94.1476342,17z/data=!4m13!1m7!3m6!1s0x87c96b79e8693b4d:0xa8a0bd1a1a77f22a!2sS+Thompson+St,+Fayetteville,+AR!3b1!8m2!3d36.1338612!4d-94.1454455!3m4!1s0x0:0x885647161671d0f!8m2!3d36.1345648!4d-94.146038

**Comment by waynemz** [comment]
Is this a non-issue?

**Comment by KKAY99** [comment]
This is a non issue.
