### ISSUE TITLE
Need service to get volunteers.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#25]
Need service to get volunteers. One that returns all volunteers as the user has the permissions to edit all volunteers, and one that returns volunteers based on organization as long as the user has the permissions to edit volunteers in that organization.

**Comment by jeff3parker** [comment]
use this service:

/users/organizations/{orgId}/roles{roleId} where role-id = 3 = VOLUNTEER

You can use /users/roles to get a list of all roles defined in the system

**Comment by Justin-Palmer** [comment]
Functionality still needed for super admin.

**Comment by jeff3parker** [comment]
Done
