### ISSUE TITLE
Need to service to get clients.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#26]
Need service to get clients. One that returns all clients as long as the user has the permissions to edit all clients., and one that returns clients based on organization as long as the user has the permissions to edit clients in that organization.

**Comment by jeff3parker** [comment]
should use /users/organizations/{org-id}/roles{role-id} to get clients.  role-id = 4 = CLIENT

use the permissions from /security/authorization to determine edit permissions.

**Comment by Justin-Palmer** [comment]
Functionality still needed for super admin.

**Comment by john3parker** [comment]
Define the functionality required for super admin. Seems like the above implementation should work for all.

**Comment by Justin-Palmer** [comment]
Super admins see all clients for all organizations, so I need a call that will return all clients for all organizations. The service should check the token sent back and make sure the one calling is a superadmin, and then return the clients.

**Comment by jeff3parker** [comment]
Done
/Users/organizations?role is=xx
