### ISSUE TITLE
Need service to get orders based on criteria.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#27]
Need service to get the next available order of a certain restaurant based on the time the order was created. 

I will send the restaurant identifier with the request, and it should return the next available order associated with that restaurant. If no identifier is received or if the isn't an order associated with that restaurant available, then the service should return the next order available based on the time the order was created.

**Comment by Bekreth** [comment]
Currently working on this.

**Comment by Bekreth** [comment]
https://github.com/hungernotimpossible/hni/pull/34

**Comment by waynemz** [comment]
@Justin-Palmer - does @Bekreth 's PR fix this issue?

**Comment by jeff3parker** [comment]
No.  Do you want to pass the providerId (e.g. Subway) or the providerLocationId (Subway at 123 Main St)?

**Comment by jeff3parker** [comment]
Duplicate/done
