### ISSUE TITLE
User object needs an id for persistence and retrieval

### ISSUE THREAD

**Issue by bbourqu** [hungernotimpossible/hni#3]
The User object didn't have an id while coding for pull request #2 it should be added.

**Comment by KKAY99** [comment]
Agreed.   Originally we thought the phone number or Email would act as the
unique idea identifier but given how fluid those values are for these users
we need a separate ID

**Comment by jeff3parker** [comment]
The User object has a Long Id.  Are you asking for a different unique identifier?

**Comment by bbourqu** [comment]
You know what it was...I would like to see it as part of the constructor. `User user = new User(id);` is more succulent than `User user = new User();  user.setId(id)l`  Forgive me its much past my bedtime 😄

**Comment by KKAY99** [comment]
I was confusing User with Customer but I realize we actually added a CustomerID to that table as well.  Looks like Both have IDs.

**Comment by jeff3parker** [comment]
done
