### ISSUE TITLE
SMS CallFlow - GetLocations

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#35]
Need a service to take in customer ID (long), address (string), items per page, and page number.

It should then respond with a JSON list of locations including the name of the location, location ID, and street address.  The list should be <items per page> and be that page number of results. (for example if the values where 3 and 2 it would provide the locations that were 4 -6 on the list of potential results. 

The list of locations should be sorted by distance from the input address and need to be checked to make sure they are currently open.  We should only return one instance of each provider type (for example one subway) per page. 

It needs to return error codes for invalid input address and a seperate error message for no available locations at this hour

**Comment by waynemz** [comment]
This issue is completed.
