### ISSUE TITLE
SMS CallFlow - CreateOrder 

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#36]
Need a service to create the customer orders during call flow.  Need to take in customer and location and then either allow me to create an order and add items to it or pass in JSON list with the cart items.

will need to update the orders table with the order information and return a result back with the order number.

**Comment by jeff3parker** [comment]
move the SMS workflow over to the HNI project as a module and then tie in the existing OrderService layer to handle order creates.

**Comment by waynemz** [comment]
Anthony Crespo and Chris Hughes are working on this

**Comment by jeff3parker** [comment]
update on progress?

**Comment by waynemz** [comment]
This issue is completed in #95
