### ISSUE TITLE
Need new authentication service.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#37]
Need new authentication service for 3rd party accounts. Google will be fine for now, but more will probably be added in the future. On the front end I'll get a token pertaining to a 3rd party account. 

I will then send the token along with the 3rd party identifier (for example 'google') to the service. The service then needs to use the token to make a call to the 3rd party api to get the user information (googles would be ""https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=" + token"). Then the service should associate the email gotten from the 3rd party to an hni user account and send back the relevant user information.

**Comment by jeff3parker** [comment]
google auth is integrated now working
