### ISSUE TITLE
CallFlow - Need Create Customer Service

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#39]
Need Service to Create CustomerFrom TextMessaging Flow

**Comment by waynemz** [comment]
@avirneni9 will be working on this

**Comment by jeff3parker** [comment]
Wayne, leverage the existing hni-user module to create new "customers" with a role of Client associated to the organization that dispensed the token they used to sign up.

**Comment by KKAY99** [comment]
One thing to note is that one client may be associated with multiple
organizations with  activations from more than one organization.

**Comment by waynemz** [comment]
@avirneni9 and @st2654 are working on this

**Comment by jeff3parker** [comment]
user associations to multiple organizations is supported: OrganizationUserService

**Comment by st2654** [comment]
@KKAY99 Do client has to register everytime with different authcode when they want to be associated with different organizations?

**Comment by KKAY99** [comment]
They would only register as a user one time.   They can add multiple auth
codes whenever they want.  If a phone is already registered and it tries to
register it should confirm their identity and then allow them to add an
auth code.


<http://mailstat.us/tr/opt-out?guid=63f49j52gafuxgcd81714iivlzz6kk>
<http://mailstat.us/tr/t/dummy>

**Comment by st2654** [comment]
This ticket needs to be closed.
It got integrated with PR# 61
@jeff3parker please close this ticket.
