### ISSUE TITLE
Move logic from textmessaging repo to Event Service

### ISSUE THREAD

**Issue by waynemz** [hungernotimpossible/hni#45]
Assign to @seoklee and @Yichao-Yu

**Comment by KKAY99** [comment]
The most current version of the code is not checked in yet.

**Comment by waynemz** [comment]
We're focussed on the logic inside the Workflow.java file. Are there any big changes to that file?

**Comment by KKAY99** [comment]
Logic wise - no, but code wise a number of the functions, especially around
registration have been updated.

**Comment by waynemz** [comment]
This issue is completed in #95
