### ISSUE TITLE
Get next available payment card info

### ISSUE THREAD

**Issue by john3parker** [hungernotimpossible/hni#49]
Input fields: orderId, orderAmount 

Need a service to retrieve the next available payment card(s) to cover the total amount for an order. Use the orderId to retrieve the order to know which QSR (Subway, Taco Bell, etc) is being used so you can retrieve a card for that QSR. You'll need to rotate through the cards in a round-robin type fashion to prevent QSR fraud detection systems from rejecting the payment card (ie. you can't use the same card twice in succession or it will freeze the card for a period of time.)

Track which payment card(s) were used to pay for an order, which user the payment card was sent to (who viewed it), how much is left on a payment card, last time the payment card was used. 

Update the order with the order amount.

**Comment by Justin-Palmer** [comment]
To add to this:

The user will input an amount needed for the order. As long as this is within an acceptable margin, the service should return card(s) which add up to the total amount of the order. Even if there is more money on the card, it should return that it only has the amount needed for completing the order.

When the order is completed, the card numbers along with the amount used will be sent back.

**Comment by jeff3parker** [comment]
This service can be used to get Collection<payment-instruments>
GET /payments/payment-instruments?providerId=XX&amount=yy.yy
