### ISSUE TITLE
Need services to allow header token.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#6]
Need services to allow header field token for sending the authentication token during service calls.

**Comment by jeff3parker** [comment]
Might be able to leverage @Context SecurityContext security in the calls to grab the header.  Future options should probably leverage an OAuth implementation.

**Comment by eldrelore** [comment]
Currently sending as part of body.  Changes to include in header instead are fairly simple, should we want to go that route.  What's the desired name of header?

**Comment by bbourqu** [comment]
Did we figure out a security provider at the moment or should we just provide a simple implementation like spring-security-oauth?  We'd have to do both the provider and the consumer if that was the case.
