### ISSUE TITLE
usermessage service - invalid email returns confusing message

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#71]
Service appears to check for valid email address but when a @ is missing it returns a value of "We didn't get that. Please send your email address."

**Comment by seoklee** [comment]
I am planning on to make the message as "Invalid Response - Please send a valid email address."

Is this okay or do you suggest a different message?

**Comment by KKAY99** [comment]
I think it might be a little "techy" for our user groups.  - Maybe "I'm sorry that is not a valid email. Please send a valid email addresss."

**Comment by seoklee** [comment]
I see. I will change it to the message you suggested.

**Comment by KKAY99** [comment]
New message working as expected.
