### ISSUE TITLE
usermessage - Return Errors

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#74]
West is expecting us to handle all errors and return errors in standardized format (not with the Tomcat exception handler) - 

Response
Status	Response
200	Response will be an object containing the next response for the user

{
  "message" :[
	"Which Location do you want",
	"1. Subway, 100 Redwood Street",
	"2. Taco Bell, 200 Walnut Road",
	"3. Togo, 1 Center Place"
  ]
}
400	{"error":"Invalid API Key"}
400	{"error":"Invalid session ID."}
400	{"error":"Invalid phone."}
500	{"error":"Something went wrong. Please try again later."}

**Comment by waynemz** [comment]
This is completed
