### ISSUE TITLE
usermessage - Message format not returning in expected format for WEST

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#75]
Status	Response
200	Response will be an object containing the next response for the user

{
  "message" :[
	"Which Location do you want",
	"1. Subway, 100 Redwood Street",
	"2. Taco Bell, 200 Walnut Road",
	"3. Togo, 1 Center Place"
  ]
}
400	{"error":"Invalid API Key"}
400	{"error":"Invalid session ID."}
400	{"error":"Invalid phone."}
500	{"error":"Something went wrong. Please try again later."}

**Comment by darargon** [comment]
How would the line separate elements of "message" be interpreted? Would they be separate lines in one text, or multiple texts? Currently Chris and I were returning one string with the newline character  to separate lines, would that format still be acceptable, or should we split it like your example?

**Comment by KKAY99** [comment]
It needs to be string back to West and they'll parse up the message back across multiple SMS messages.  Newline characters are not recommended in the SMS flow

**Comment by waynemz** [comment]
this is completed in #96
