### ISSUE TITLE
usermessage - registration - same auth code multiple times

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#76]
auth codes are not marked as used and can be used multiple times during the registration (or so the user prompts suggest)

**Comment by Yichao-Yu** [comment]
it is due to UserService being injected in RegisterService. But it is supposed to be CustomerService

**Comment by seoklee** [comment]
I think it should be more of ActivationCodeService; it should not check a valid check if code is already activated. (which is more like checking if ActivationCode has a User linked to it)

**Comment by KKAY99** [comment]
tested and working as expected
