### ISSUE TITLE
Need user firstName and lastName returned with order.

### ISSUE THREAD

**Issue by Justin-Palmer** [hungernotimpossible/hni#87]

**Comment by KKAY99** [comment]
Justin,  Do we need last name or can we just use First Name? I think to
respect privacy we want to avoid Last Name.  If we need last name field
maybe we just use first letter ?   Ideally it would be good to just give
Justin as a name or Justin P. as a fallback.

**Comment by Justin-Palmer** [comment]
The design was first and last name, but that's a good point. I guess for now you send me the full name and I can truncate it to just use the initial for the last name on the display. That it can be returned truncated already, I'd be fine with either.

**Comment by jeff3parker** [comment]
Added M:1 => User on Order object, rendered back only id, first/last
