### ISSUE TITLE
schema - hours of availability need to be at the menu item level not the menu level

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#9]

**Comment by jeff3parker** [comment]
I'm not so sure we need to do this.  Typically menus provide items that are grouped together on availability times.  And having people manage hour availability per item would be a lot of work.

**Comment by jeff3parker** [comment]
Sure why not?  That seems to be how they think about their menu as well.  Then the management of items is pretty simple and they just need to add hours of availability to a menu.
